name: Docker Image CI Test

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
        
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@master
        
    - name: build the image
      run: |
        docker buildx build --push \
          --tag $DOCKER_USER/$REPO_NAME:test \
          --tag $DOCKER_USER/$REPO_NAME:test-${{ steps.date.outputs.date }} \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
