name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Get current date # get the date of the build
      id: date
      run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_OUTPUT"
      
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@master
        
    - name: build the image
      run: |
        docker buildx build --push \
          --tag ${{ secrets.DOCKER_USER }}/${{secrets.REPO_NAME}}:latest \
          --tag ${{ secrets.DOCKER_USER }}/${{secrets.REPO_NAME}}:master-${{ steps.date.outputs.date }} \
          --platform linux/amd64,linux/arm64 .